theme: jekyll-theme-minimal
title: UAVA 
show_downloads: false
description: A dataset for UAV assistant tasks

github:
    repository_url: https://github.com/VCL3D/UAVA
    is_project_page: true
    repository_name: UAVA
    owner_url: https://github.com/tzole1155
    owner_name: Giorgos Albanis


google_analytics: UA-176089043-1
